/*
Author: Luca Scaringella
GitHub: LucaCode
Copyright(c) Luca Scaringella
 */

export enum ClientErrorName {
    ID_MISSING                   = 'IS_MISSING',
    UNKNOWN_ID                   = 'UNKNOWN_ID',
    NAME_MISSING                 = 'NAME_MISSING',
    UNKNOWN_CHANNEL              = 'UNKNOWN_CHANNEL',
    NO_ACCESS_WITH_VERSION       = 'NO_ACCESS_WITH_VERSION',
    NO_ACCESS_WITH_SYSTEM        = 'NO_ACCESS_WITH_SYSTEM',
    ACCESS_DENIED                = 'ACCESS_DENIED',
    ID_IS_NOT_VALID              = 'ID_IS_NOT_VALID',

    INVALID_REQUEST              = 'INVALID_REQUEST',
    API_LEVEL_NOT_COMPATIBLE     = 'API_LEVEL_NOT_COMPATIBLE',
    UNKNOWN_DATABOX              = 'UNKNOWN_DATABOX',
    DATABOX_LIMIT_REACHED        = 'DATABOX_LIMIT_REACHED',
    UNKNOWN_SESSION_TARGET       = 'UNKNOWN_SESSION_TARGET',
    UNKNOWN_ACTION               = 'UNKNOWN_ACTION',
    NO_MORE_DATA_AVAILABLE       = 'NO_MORE_DATA_AVAILABLE',
    NO_DATA_AVAILABLE            = 'NO_DATA_AVAILABLE',
    MAX_BACKPRESSURE_REACHED     = 'MAX_BACKPRESSURE_REACHED',
    INVALID_INPUT                = 'INVALID_INPUT',
    MAX_INPUT_CHANNELS_REACHED   = 'MAX_INPUT_CHANNELS_REACHED',
}